# Generated by Django 5.2 on 2025-05-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('perfil', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
