# Generated by Django 5.2 on 2025-05-20 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=9)),
                ('morada', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('equipamento', models.CharField(max_length=100)),
                ('defeito', models.TextField()),
                ('servico', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tecnico', models.CharField(max_length=50)),
                ('situacao', models.CharField(choices=[('na_bancada', 'Na Bancada'), ('aguardando_pecas', 'Aguardando Peças'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('abandonado', 'Abandonado pelo Cliente'), ('retornou', 'Retornou'), ('orcamento_reprovado', 'Orçamento Reprovado')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistencia.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
