# Generated by Django 5.2 on 2025-05-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0002_cliente_ordemdeservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('U', 'User'), ('A', 'Admin')], max_length=1),
        ),
    ]
