# Generated by Django 5.2 on 2025-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0003_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.CharField(max_length=50, unique=True, verbose_name='Login de acesso'),
        ),
    ]
